In [14]:
import pandas as pd
import numpy as np

# Relative path to the dataset
file_path = "../Dataset/alzheimers_disease_data.csv"

## Creating an array
array = np.arange(15).reshape(3, 5)
print(array)

# Load the dataset
data = pd.read_csv(file_path)

print(data) # Display the first 5 and last 5 rows

data_type_of_elements = data.dtypes
print(data_type_of_elements) ## Prints data type of the variables

size_of_Axis = data.shape
print(size_of_Axis) ## Prints data type of the variables



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
      PatientID  Age  Gender  Ethnicity  EducationLevel        BMI  Smoking  \
0          4751   73       0          0               2  22.927749        0   
1          4752   89       0          0               0  26.827681        0   
2          4753   73       0          3               1  17.795882        0   
3          4754   74       1          0               1  33.800817        1   
4          4755   89       0          0               0  20.716974        0   
...         ...  ...     ...        ...             ...        ...      ...   
2144       6895   61       0          0               1  39.121757        0   
2145       6896   75       0          0               2  17.857903        0   
2146       6897   77       0          0               1  15.476479        0   
2147       6898   78       1          3               1  15.299911        0   
2148       6899   72       0          0               2  33.289738        0 